version: 0.0
os: linux
files:
  - source: /src
    destination: /srv/www/aws.innovator-jp.info
permissions:
  - object: /srv/www/aws.innovator-jp.info 
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
hooks:
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 600
