version: '3'
services:
    nginx:
        image: nginx:alpine
        ports:
          - "80:80"
        volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./:/var/www/app
    php:
        build: ./docker/php
        volumes:
          - ./:/var/www/app
    mysql:
        image: mysql:5.7
        volumes:
          - aamdb:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=aws_account_manager
volumes:
    aamdb:
        driver: local

