version: '2'
services:
    sqldata:
        image: alpine
        volumes:
          - ./public:/var/www/html
    wwwdata:
        image: alpine
        volumes:
          - ./public:/var/www/html
    nginx:
        build: ./docker/nginx
        ports:
          - "8000:80"
        links:
          - php
        volumes:
          - ./docker/nginx/server.conf:/etc/nginx/conf.d/server.conf
        volumes_from:
          - wwwdata
    php:
      build: ./docker/php
      links:
        - db
      volumes:
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      volumes_from:
        - wwwdata
      depends_on:
        - "db"
    db:
      image: mysql
      volumes_from:
        - sqldata
      environment:
        MYSQL_ROOT_PASSWORD: "password"
        MYSQL_DATABASE: "aws_account_manager"
        TZ: "Asia/Tokyo"
